[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://oooxngcquideicyrqmvo.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vb3huZ2NxdWlkZWljeXJxbXZvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODEzNzQ3MSwiZXhwIjoyMDYzNzEzNDcxfQ.3-uA7enEKS8uJpU1KkeRjVuuDqegLcmOm3MM1ou4fwQ"

[[plugins]]
  package = "@netlify/plugin-nextjs" 