// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oooxngcquideicyrqmvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vb3huZ2NxdWlkZWljeXJxbXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzc0NzEsImV4cCI6MjA2MzcxMzQ3MX0.kwWliJenUanKr-xheFNozTT9m2HQY80WL3lkHIPEkcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);